version: "3"
services:
  zookeeper:
    image: test-eventuate-zookeeper
    ports:
      - 2181:2181


  kafka:
    image: test-eventuate-kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181

  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
      - 1883:1883
      - 61614:61614

  mysql:
    build:
      context: ./mysql
      args:
        EVENTUATE_TRAM_VERSION: "$EVENTUATE_TRAM_VERSION"
        EVENTUATE_LOCAL_VERSION: "$EVENTUATE_LOCAL_VERSION"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  cdcservice:
    image: test-eventuate-cdc-service
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka
      - activemq
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATE_CURRENT_TIME_IN_MILLISECONDS_SQL: ${EVENTUATE_CURRENT_TIME_IN_MILLISECONDS_SQL}
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1234567890
      EVENTUATELOCAL_CDC_MY_SQL_BIN_LOG_CLIENT_NAME: 1234567890
      EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
      EVENTUATELOCAL_CDC_READER_NAME: ClientEventuateTram
      EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: 2
      ACTIVEMQ_URL: tcp://activemq:61616
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
